Syzkaller hit 'BUG: MAX_LOCKDEP_KEYS too low!' bug.

BUG: MAX_LOCKDEP_KEYS too low!
turning off the locking correctness validator.
CPU: 1 PID: 39188 Comm: syz.5.3249 Not tainted 6.8.0 #1
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014
Call Trace:
 <TASK>
 __dump_stack lib/dump_stack.c:88 [inline]
 dump_stack_lvl+0xea/0x170 lib/dump_stack.c:106
 register_lock_class+0x2d2/0x2f0 kernel/locking/lockdep.c:1321
 __lock_acquire+0x6c/0xc10 kernel/locking/lockdep.c:5014
 lock_acquire+0xcb/0x1d0 kernel/locking/lockdep.c:5754
 __flush_workqueue+0x95/0x830 kernel/workqueue.c:3146
 drain_workqueue+0x79/0x1d0 kernel/workqueue.c:3311
 destroy_workqueue+0x66/0x730 kernel/workqueue.c:4793
 nci_unregister_device+0x38/0xd0 net/nfc/nci/core.c:1304
 virtual_ncidev_close+0x18/0x40 drivers/nfc/virtual_ncidev.c:168
 __fput+0x1d8/0x550 fs/file_table.c:376
 task_work_run+0xc9/0x110 kernel/task_work.c:180
 resume_user_mode_work include/linux/resume_user_mode.h:50 [inline]
 exit_to_user_mode_loop kernel/entry/common.c:108 [inline]
 exit_to_user_mode_prepare include/linux/entry-common.h:328 [inline]
 __syscall_exit_to_user_mode_work kernel/entry/common.c:201 [inline]
 syscall_exit_to_user_mode+0x111/0x260 kernel/entry/common.c:212
 do_syscall_64+0x8e/0x150 arch/x86/entry/common.c:89
 entry_SYSCALL_64_after_hwframe+0x63/0x6b
RIP: 0033:0x7f01ef5ae16d
Code: 02 b8 ff ff ff ff c3 66 0f 1f 44 00 00 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 c7 c1 a8 ff ff ff f7 d8 64 89 01 48
RSP: 002b:00007fffe2bfcc98 EFLAGS: 00000246 ORIG_RAX: 00000000000001b4
RAX: 0000000000000000 RBX: 0000000000000000 RCX: 00007f01ef5ae16d
RDX: 0000000000000000 RSI: 000000000000001e RDI: 0000000000000003
RBP: 00007fffe2bfcd38 R08: 0000001b2f3200d7 R09: 0000000000000000
R10: 0000001b2f720000 R11: 0000000000000246 R12: ffffffffffffffff
R13: 00007f01ef7f5fac R14: 00007f01ef7f5fa0 R15: 0000000000000000
 </TASK>


Syzkaller reproducer:
# {Threaded:false Repeat:true RepeatTimes:0 Procs:8 Slowdown:1 Sandbox: SandboxArg:0 Leak:false NetInjection:false NetDevices:false NetReset:false Cgroups:false BinfmtMisc:false CloseFDs:false KCSAN:false DevlinkPCI:false NicVF:false USB:false VhciInjection:false Wifi:false IEEE802154:false Sysctl:false Swap:false UseTmpDir:false HandleSegv:false Trace:false CallComments:true LegacyOptions:{Collide:false Fault:false FaultCall:0 FaultNth:0}}
r0 = openat$nci(0xffffffffffffff9c, &(0x7f0000000080), 0x2, 0x0)
write$nci(r0, 0x0, 0x0)
write$nci(r0, 0x0, 0x0)
write$nci(r0, 0x0, 0x0)
sendmsg$NFC_CMD_START_POLL(0xffffffffffffffff, 0x0, 0x0)
write$nci(r0, 0x0, 0x0)
write$nci(r0, 0x0, 0x0)
write$nci(r0, 0x0, 0x0)
write$nci(r0, 0x0, 0x0)


C reproducer:
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[1] = {0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  openat$nci arguments: [
  //    fd: const = 0xffffffffffffff9c (8 bytes)
  //    file: ptr[in, buffer] {
  //      buffer: {2f 64 65 76 2f 76 69 72 74 75 61 6c 5f 6e 63 69 00} (length
  //      0x11)
  //    }
  //    flags: const = 0x2 (4 bytes)
  //    mode: const = 0x0 (2 bytes)
  //  ]
  //  returns fd_nci
  memcpy((void*)0x200000000080, "/dev/virtual_nci\000", 17);
  res = syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul,
                /*file=*/0x200000000080ul, /*flags=*/2, /*mode=*/0);
  if (res != -1)
    r[0] = res;
  //  write$nci arguments: [
  //    fd: fd_nci (resource)
  //    data: nil
  //    len: bytesize = 0x0 (8 bytes)
  //  ]
  syscall(__NR_write, /*fd=*/r[0], /*data=*/0ul, /*len=*/0ul);
  //  write$nci arguments: [
  //    fd: fd_nci (resource)
  //    data: nil
  //    len: bytesize = 0x0 (8 bytes)
  //  ]
  syscall(__NR_write, /*fd=*/r[0], /*data=*/0ul, /*len=*/0ul);
  //  write$nci arguments: [
  //    fd: fd_nci (resource)
  //    data: nil
  //    len: bytesize = 0x0 (8 bytes)
  //  ]
  syscall(__NR_write, /*fd=*/r[0], /*data=*/0ul, /*len=*/0ul);
  //  sendmsg$NFC_CMD_START_POLL arguments: [
  //    fd: sock_nl_generic_init (resource)
  //    msg: nil
  //    f: send_flags = 0x0 (8 bytes)
  //  ]
  syscall(__NR_sendmsg, /*fd=*/(intptr_t)-1, /*msg=*/0ul, /*f=*/0ul);
  //  write$nci arguments: [
  //    fd: fd_nci (resource)
  //    data: nil
  //    len: bytesize = 0x0 (8 bytes)
  //  ]
  syscall(__NR_write, /*fd=*/r[0], /*data=*/0ul, /*len=*/0ul);
  //  write$nci arguments: [
  //    fd: fd_nci (resource)
  //    data: nil
  //    len: bytesize = 0x0 (8 bytes)
  //  ]
  syscall(__NR_write, /*fd=*/r[0], /*data=*/0ul, /*len=*/0ul);
  //  write$nci arguments: [
  //    fd: fd_nci (resource)
  //    data: nil
  //    len: bytesize = 0x0 (8 bytes)
  //  ]
  syscall(__NR_write, /*fd=*/r[0], /*data=*/0ul, /*len=*/0ul);
  //  write$nci arguments: [
  //    fd: fd_nci (resource)
  //    data: nil
  //    len: bytesize = 0x0 (8 bytes)
  //  ]
  syscall(__NR_write, /*fd=*/r[0], /*data=*/0ul, /*len=*/0ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  for (procid = 0; procid < 8; procid++) {
    if (fork() == 0) {
      loop();
    }
  }
  sleep(1000000);
  return 0;
}
